//! Static catalog of discoverable UEFI/PI protocol GUIDs, used by the
//! Features screen to report which ones this firmware actually implements.
//!
//! Generated from `tianocore/edk2` protocol headers (`MdePkg`, `MdeModulePkg`,
//! `SecurityPkg`, `NetworkPkg`) -- GUIDs and descriptions are taken directly
//! from each header rather than hand-typed, to avoid transcription errors.
//! Excludes protocols only ever installed by DXE/SMM/PEI modules talking to
//! each other (the PI driver-model and SMM/MM dispatch families), which a
//! boot-time application has no way to observe. See
//! `docs/uefi-and-hda-architecture.typ`, Appendix A, for the full picture.

use uefi::{Guid, guid};

pub struct ProtocolEntry {
    pub category: &'static str,
    pub name: &'static str,
    pub guid: Guid,
    pub description: &'static str,
}

pub static CATALOG: &[ProtocolEntry] = &[
    ProtocolEntry {
        category: "Console, Input & Serial I/O",
        name: "AbsolutePointer",
        guid: guid!("8d59d32b-c655-4ae9-9b15-f25904992a43"),
        description: "The file provides services that allow information about an absolute pointer device to be retrieved.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "AdapterInformation",
        guid: guid!("e5dd1403-d622-c24e-8488-c71b17f5e802"),
        description: "EFI Adapter Information Protocol definition. The EFI Adapter Information Protocol is used to dynamically and quickly discover or set device information for an adapter.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Arp",
        guid: guid!("f4b427bb-ba21-4f16-bc4e-43e416ab619c"),
        description: "EFI ARP Protocol Definition The EFI ARP Service Binding Protocol is used to locate EFI ARP Protocol drivers to create and destroy child of the driver to communicate with other host using ARP protocol. The EFI ARP Protocol provides services to map IP network address to hardware address used by a data link protocol.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "AtaPassThru",
        guid: guid!("1d3de7f0-0807-424f-aa69-11a54e19a46f"),
        description: "The EFI_ATA_PASS_THRU_PROTOCOL provides information about an ATA controller and the ability to send ATA Command Blocks to any ATA device attached to that ATA controller. The information includes the attributes of the ATA controller.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "AuthenticationInfo",
        guid: guid!("7671d9d0-53db-4173-aa69-2327f21f0bc7"),
        description: "EFI_AUTHENTICATION_INFO_PROTOCOL as defined in UEFI 2.0. This protocol is used on any device handle to obtain authentication information associated with the physical or logical device.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "Bds",
        guid: guid!("665e3ff6-46cc-11d4-9a38-0090273fc14d"),
        description: "Boot Device Selection Architectural Protocol as defined in PI spec Volume 2 DXE When the DXE core is done it calls the BDS via this protocol.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "Bis",
        guid: guid!("0b64aab0-5429-11d4-9816-00a0c91fadcf"),
        description: "The EFI_BIS_PROTOCOL is used to check a digital signature of a data block against a digital certificate for the purpose of an integrity and authorization check.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "BlockIo",
        guid: guid!("964e5b21-6459-11d2-8e39-00a0c969723b"),
        description: "Block IO protocol as defined in the UEFI 2.0 specification. The Block IO protocol is used to abstract block devices like hard drives, DVD-ROMs and floppy drives.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "BlockIo2",
        guid: guid!("a77b2472-e282-4e9f-a245-c2c0e27bbcc1"),
        description: "Block IO2 protocol as defined in the UEFI 2.3.1 specification. The Block IO2 protocol defines an extension to the Block IO protocol which enables the ability to read and write data at a block level in a non-blocking manner.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "BlockIoCrypto",
        guid: guid!("a00490ba-3f1a-4b4c-ab90-4fa99726a1e8"),
        description: "The UEFI Inline Cryptographic Interface protocol provides services to abstract access to inline cryptographic capabilities.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "BluetoothAttribute",
        guid: guid!("898890e9-84b2-4f3a-8c58-d8577813e0ac"),
        description: "EFI Bluetooth Attribute Protocol as defined in UEFI 2.7. This protocol provides service for Bluetooth ATT (Attribute Protocol) and GATT (Generic Attribute Profile) based protocol interfaces.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "BluetoothConfig",
        guid: guid!("62960cf3-40ff-4263-a77c-dfdebd191b4b"),
        description: "EFI Bluetooth Configuration Protocol as defined in UEFI 2.7. This protocol abstracts user interface configuration for Bluetooth device.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "BluetoothHc",
        guid: guid!("b3930571-beba-4fc5-9203-9427242e6a43"),
        description: "EFI Bluetooth Host Controller Protocol as defined in UEFI 2.5. This protocol abstracts the Bluetooth host controller layer message transmit and receive.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "BluetoothIo",
        guid: guid!("467313de-4e30-43f1-943e-323f89845db5"),
        description: "EFI Bluetooth IO Service Binding Protocol as defined in UEFI 2.5. EFI Bluetooth IO Protocol as defined in UEFI 2.5.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "BluetoothLeConfig",
        guid: guid!("8f76da58-1f99-4275-a4ec-4756515b1ce8"),
        description: "EFI Bluetooth LE Config Protocol as defined in UEFI 2.7. This protocol abstracts user interface configuration for BluetoothLe device.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "BootManagerPolicy",
        guid: guid!("fedf8e0c-e147-11e3-9903-b8e8562cbafa"),
        description: "Boot Manager Policy Protocol as defined in UEFI Specification. This protocol is used by EFI Applications to request the UEFI Boot Manager to connect devices using platform policy.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "Capsule",
        guid: guid!("5053697e-2cbc-4819-90d9-0580deee5754"),
        description: "Capsule Architectural Protocol as defined in PI1.0a Specification VOLUME 2 DXE The DXE Driver that produces this protocol must be a runtime driver. The driver is responsible for initializing the CapsuleUpdate() and QueryCapsuleCapabilities() fields of the UEFI Runtime Services Table.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "CcMeasurement",
        guid: guid!("96751a3d-72f4-41a6-a794-ed5d0e67ae6b"),
        description: "If CC Guest firmware supports measurement and an event is created, CC Guest firmware is designed to report the event log with the same data structure in TCG-Platform-Firmware-Profile specification with EFI_TCG2_EVENT_LOG_FORMAT_TCG_2 format. The CC Guest firmware supports measurement, the CC Guest Firmware is designed to produce EFI_CC_MEASUREMENT_PROTOCOL with new GUID EFI_CC_MEASUREMENT_PROTOCOL_GUID to report event log and provides hash capability.",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "Cpu",
        guid: guid!("26baccb1-6f42-11d4-bce7-0080c73c8881"),
        description: "CPU Architectural Protocol as defined in PI spec Volume 2 DXE This code abstracts the DXE core from processor implementation details.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "CpuIo2",
        guid: guid!("ad61f191-ae5f-4c0e-b9fa-e869d288c64f"),
        description: "This files describes the CPU I/O 2 Protocol. This protocol provides an I/O abstraction for a system processor.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "DebugPort",
        guid: guid!("eba4e8d2-3858-41ec-a281-2647ba9660d0"),
        description: "The file defines the EFI Debugport protocol. This protocol is used by debug agent to communicate with the remote debug host.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "DebugSupport",
        guid: guid!("2755590c-6f3c-42fa-9ea4-a3ba543cda25"),
        description: "DebugSupport protocol and supporting definitions as defined in the UEFI2.4 specification. The DebugSupport protocol is used by source level debuggers to abstract the processor and handle context save and restore operations.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "Decompress",
        guid: guid!("d8117cfe-94a6-11d4-9a3a-0090273fc14d"),
        description: "The Decompress Protocol Interface as defined in UEFI spec",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "DeferredImageLoad",
        guid: guid!("15853d7c-3ddf-43e0-a1cb-ebf85b8f872c"),
        description: "UEFI 2.2 Deferred Image Load Protocol definition. This protocol returns information about images whose load was denied because of security considerations.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "DevicePath",
        guid: guid!("09576e91-6d3f-11d2-8e39-00a0c969723b"),
        description: "The device path protocol as defined in UEFI 2.0. The device path represents a programmatic path to a device, from a software point of view.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "DevicePathFromText",
        guid: guid!("05c99a21-c70f-4ad2-8a5f-35df3343f51e"),
        description: "EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL as defined in UEFI 2.0. This protocol provides service to convert text to device paths and device nodes.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "DevicePathToText",
        guid: guid!("8b843e20-8132-4852-90cc-551a4e4a7f1c"),
        description: "EFI_DEVICE_PATH_TO_TEXT_PROTOCOL as defined in UEFI 2.0. This protocol provides service to convert device nodes and paths to text.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "DevicePathUtilities",
        guid: guid!("0379be4e-d706-437d-b037-edb82fb772a4"),
        description: "EFI_DEVICE_PATH_UTILITIES_PROTOCOL as defined in UEFI 2.0. Use to create and manipulate device paths and device nodes.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Dhcp4",
        guid: guid!("8a219718-4ef5-4761-91c8-c0f04bda9e56"),
        description: "EFI_DHCP4_PROTOCOL as defined in UEFI 2.0. EFI_DHCP4_SERVICE_BINDING_PROTOCOL as defined in UEFI 2.0.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Dhcp6",
        guid: guid!("87c8bad7-0595-4053-8297-dede395f5d5b"),
        description: "UEFI Dynamic Host Configuration Protocol 6 Definition, which is used to get IPv6 addresses and other configuration parameters from DHCPv6 servers.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "DiskInfo",
        guid: guid!("d432a67f-14dc-484b-b3bb-3f0291849327"),
        description: "Provides the basic interfaces to abstract platform information regarding an IDE controller.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "DiskIo",
        guid: guid!("ce345171-ba0b-11d2-8e4f-00a0c969723b"),
        description: "Disk IO protocol as defined in the UEFI 2.0 specification. The Disk IO protocol is used to convert block oriented devices into byte oriented devices.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Dns4",
        guid: guid!("ae3d28cc-e05b-4fa1-a011-7eb55a3f1401"),
        description: "This file defines the EFI Domain Name Service Binding Protocol interface. It is split into the following two main sections: DNSv4 Service Binding Protocol (DNSv4SB) DNSv4 Protocol (DNSv4)",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Dns6",
        guid: guid!("ca37bc1f-a327-4ae9-828a-8c40d8506a17"),
        description: "This file defines the EFI DNSv6 (Domain Name Service version 6) Protocol. It is split into the following two main sections: DNSv6 Service Binding Protocol (DNSv6SB) DNSv6 Protocol (DNSv6)",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "DtFixup",
        guid: guid!("60ed6ba9-dfef-4799-ac7b-75e0f833456c"),
        description: "Device Tree Fixup Protocol. Modifies a device tree in memory to align it with the firmware's view of the platform.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "Eap",
        guid: guid!("5d9f96db-e731-4caa-a00d-72e187cd7762"),
        description: "EFI EAP(Extended Authenticaton Protocol) Protocol Definition The EFI EAP Protocol is used to abstract the ability to configure and extend the EAP framework. The definitions in this file are defined in UEFI Specification 2.3.1B, which have not been verified by one implementation yet.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "EapConfiguration",
        guid: guid!("e5b58dbb-7688-44b4-97bf-5f1d4b7cc8db"),
        description: "This file defines the EFI EAP Configuration protocol.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "EapManagement",
        guid: guid!("bb62e663-625d-40b2-a088-bbe83623a245"),
        description: "EFI EAP Management Protocol Definition The EFI EAP Management Protocol is designed to provide ease of management and ease of test for EAPOL state machine. It is intended for the supplicant side.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "EapManagement2",
        guid: guid!("5e93c847-456d-40b3-a6b4-78b0c9cf7f20"),
        description: "This file defines the EFI EAP Management2 protocol.",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "Ebc",
        guid: guid!("13ac6dd1-73d0-11d4-b06b-00aa00bd6de7"),
        description: "Describes the protocol interface to the EBC interpreter.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "EdidActive",
        guid: guid!("bd8c1056-9f36-44ec-92a8-a6337f817986"),
        description: "EDID Active Protocol from the UEFI 2.0 specification. Placed on the video output device child handle that is actively displaying output.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "EdidDiscovered",
        guid: guid!("1c0c34f6-d380-41fa-a049-8ad06c1a66aa"),
        description: "EDID Discovered Protocol from the UEFI 2.0 specification. This protocol is placed on the video output device child handle.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "EdidOverride",
        guid: guid!("48ecb431-fb72-45c0-a922-f458fe040bd5"),
        description: "EDID Override Protocol from the UEFI 2.0 specification. Allow platform to provide EDID information to the producer of the Graphics Output protocol.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "EraseBlock",
        guid: guid!("95a9a93e-a86e-4926-aaef-9918e772d987"),
        description: "This file defines the EFI Erase Block Protocol.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "FirmwareManagement",
        guid: guid!("86c77a67-0b97-4633-a187-49104d0685c7"),
        description: "UEFI Firmware Management Protocol definition Firmware Management Protocol provides an abstraction for device to provide firmware management support. The base requirements for managing device firmware images include identifying firmware image revision level and programming the image into the device.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "FirmwareVolume2",
        guid: guid!("220e73b6-6bdb-4413-8405-b974b108619a"),
        description: "The Firmware Volume Protocol provides file-level access to the firmware volume. Each firmware volume driver must produce an instance of the Firmware Volume Protocol if the firmware volume is to be visible to the system during the DXE phase.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "FirmwareVolumeBlock",
        guid: guid!("8f644fa9-e850-4db1-9ce2-0b44698e8da4"),
        description: "This file provides control over block-oriented firmware devices.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "FormBrowser2",
        guid: guid!("b9d4c360-bcfb-4f9b-9298-53c136982258"),
        description: "This protocol is defined in UEFI spec. The EFI_FORM_BROWSER2_PROTOCOL is the interface to call for drivers to leverage the EFI configuration driver interface.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Ftp4",
        guid: guid!("eb338826-681b-4295-b356-2b364c757b09"),
        description: "EFI FTPv4 (File Transfer Protocol version 4) Protocol Definition The EFI FTPv4 Protocol is used to locate communication devices that are supported by an EFI FTPv4 Protocol driver and to create and destroy instances of the EFI FTPv4 Protocol child protocol driver that can use the underlying communication device. The definitions in this file are defined in UEFI Specification 2.3, which have not been verified by one implementation yet.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "GraphicsOutput",
        guid: guid!("9042a9de-23dc-4a38-96fb-7aded080516a"),
        description: "Graphics Output Protocol from the UEFI 2.0 specification. Abstraction of a very simple graphics device.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Hash",
        guid: guid!("c5184932-dba5-46db-a5ba-cc0bda9c1435"),
        description: "EFI_HASH_SERVICE_BINDING_PROTOCOL as defined in UEFI 2.0. EFI_HASH_PROTOCOL as defined in UEFI 2.0.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Hash2",
        guid: guid!("55b1d734-c5e1-49db-9647-b16afb0e305b"),
        description: "EFI_HASH2_SERVICE_BINDING_PROTOCOL as defined in UEFI 2.5. EFI_HASH2_PROTOCOL as defined in UEFI 2.5.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiConfigAccess",
        guid: guid!("330d4706-f2a0-4e4f-a369-b66fa8d54385"),
        description: "The EFI HII results processing protocol invokes this type of protocol when it needs to forward results to a driver's configuration handler. This protocol is published by drivers providing and requesting configuration data from HII.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiConfigKeyword",
        guid: guid!("0a8badd5-03b8-4d19-b128-7b8f0edaa596"),
        description: "The file provides the mechanism to set and get the values associated with a keyword exposed through a x-UEFI- prefixed configuration language namespace.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiConfigRouting",
        guid: guid!("587e72d7-cc50-4f79-8209-ca291fc1a10f"),
        description: "The file provides services to manage the movement of configuration data from drivers to configuration applications. It then serves as the single point to receive configuration information from configuration applications, routing the results to the appropriate drivers.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiDatabase",
        guid: guid!("ef9fc172-a1b2-4693-b327-6d32fc416042"),
        description: "The file provides Database manager for HII-related data structures.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiFont",
        guid: guid!("e9ca4775-8657-47fc-97e7-7ed65a084324"),
        description: "The file provides services to retrieve font information.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiImage",
        guid: guid!("31a6406a-6bdf-4e46-b2a2-ebaa89c40920"),
        description: "The file provides services to access to images in the images database.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiImageDecoder",
        guid: guid!("9e66f251-727c-418c-bfd6-c2b4252818ea"),
        description: "This protocol provides generic image decoder interfaces to various image formats. (C) Copyright 2016 Hewlett Packard Enterprise Development LP<BR>",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiImageEx",
        guid: guid!("1a1241e6-8f19-41a9-bc0e-e8ef39e06546"),
        description: "Protocol which allows access to the images in the images database. (C) Copyright 2016-2018 Hewlett Packard Enterprise Development LP<BR> SPDX-License-Identifier: BSD-2-Clause-Patent",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiPackageList",
        guid: guid!("6a1ee763-d47a-43b4-aabe-ef1de2ab56fc"),
        description: "EFI_HII_PACKAGE_LIST_PROTOCOL as defined in UEFI 2.1. Boot service LoadImage() installs EFI_HII_PACKAGE_LIST_PROTOCOL on the handle if the image contains a custom PE/COFF resource with the type 'HII'.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiPopup",
        guid: guid!("4311edc0-6054-46d4-9e40-893ea952fccc"),
        description: "This protocol provides services to display a popup window. The protocol is typically produced by the forms browser and consumed by a driver callback handler.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "HiiString",
        guid: guid!("0fd96974-23aa-4cdc-b9cb-98d17750322a"),
        description: "The file provides services to manipulate string data.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "Http",
        guid: guid!("7a59b29b-910b-4171-8242-a85a0df25b5b"),
        description: "This file defines the EFI HTTP Protocol interface. It is split into the following two main sections: HTTP Service Binding Protocol (HTTPSB) HTTP Protocol (HTTP)",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "HttpBootCallback",
        guid: guid!("ba23b311-343d-11e6-9185-5820b1d65299"),
        description: "This file defines the EFI HTTP Boot Callback Protocol interface.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "HttpUtilities",
        guid: guid!("3e35c163-4074-45dd-431e-23989dd86b32"),
        description: "EFI HTTP Utilities protocol provides a platform independent abstraction for HTTP message comprehension.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "I2cBusConfigurationManagement",
        guid: guid!("55b71fb5-17c6-410e-b5bd-5fa2e3d4466b"),
        description: "I2C Bus Configuration Management Protocol as defined in the PI 1.3 specification. The EFI I2C bus configuration management protocol provides platform specific services that allow the I2C host protocol to reconfigure the switches and multiplexers and set the clock frequency for the I2C bus.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "IScsiInitiatorName",
        guid: guid!("59324945-ec44-4c0d-b1cd-9db139df070c"),
        description: "EFI_ISCSI_INITIATOR_NAME_PROTOCOL as defined in UEFI 2.0. It provides the ability to get and set the iSCSI Initiator Name.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "IdeControllerInit",
        guid: guid!("a1e37052-80d9-4e65-a317-3e9a55c43ec9"),
        description: "This file declares EFI IDE Controller Init Protocol The EFI_IDE_CONTROLLER_INIT_PROTOCOL provides the chipset-specific information to the driver entity. This protocol is mandatory for IDE controllers if the IDE devices behind the controller are to be enumerated by a driver entity.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "IncompatiblePciDeviceSupport",
        guid: guid!("eb23f55a-7863-4ac2-8d3d-956535de0375"),
        description: "This file declares Incompatible PCI Device Support Protocol Allows the PCI bus driver to support resource allocation for some PCI devices that do not comply with the PCI Specification.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Ip4",
        guid: guid!("41d94cd2-35b6-455a-8258-d4e51334aadd"),
        description: "This file defines the EFI IPv4 (Internet Protocol version 4) Protocol interface. It is split into the following three main sections: - EFI IPv4 Service Binding Protocol - EFI IPv4 Variable (deprecated in UEFI 2.4B) - EFI IPv4 Protocol.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Ip4Config2",
        guid: guid!("5b446ed1-e30b-4faa-871a-3654eca36080"),
        description: "This file provides a definition of the EFI IPv4 Configuration II Protocol.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Ip6",
        guid: guid!("2c8759d5-5c2d-66ef-925f-b66c101957e2"),
        description: "This file defines the EFI IPv6 (Internet Protocol version 6) Protocol interface. It is split into the following three main sections: - EFI IPv6 Service Binding Protocol - EFI IPv6 Variable (deprecated in UEFI 2.4B) - EFI IPv6 Protocol The EFI IPv6 Protocol provides basic network IPv6 packet I/O services, which includes support for Neighbor Discovery Protocol (ND), Multicast Listener Discovery Protocol (MLD), and a subset of the Internet Control Message Protocol (ICMPv6).",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Ip6Config",
        guid: guid!("937fe521-95ae-4d1a-8929-48bcd90ad31a"),
        description: "This file provides a definition of the EFI IPv6 Configuration Protocol.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "IpSec",
        guid: guid!("dfb386f7-e100-43ad-9c9a-ed90d08a5e12"),
        description: "EFI IPSEC Protocol Definition The EFI_IPSEC_PROTOCOL is used to abstract the ability to deal with the individual packets sent and received by the host and provide packet-level security for IP datagram. The EFI_IPSEC2_PROTOCOL is used to abstract the ability to deal with the individual packets sent and received by the host and provide packet-level security for IP datagram.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "IpSecConfig",
        guid: guid!("ce5e5929-c7a3-4602-ad9e-c9daf94ebfcf"),
        description: "EFI IPsec Configuration Protocol Definition The EFI_IPSEC_CONFIG_PROTOCOL provides the mechanism to set and retrieve security and policy related information for the EFI IPsec protocol driver.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "IsaHc",
        guid: guid!("bcdaf080-1bde-4e22-ae6a-43541e128ec4"),
        description: "ISA HC Protocol as defined in the PI 1.2.1 specification. This protocol provides registration for ISA devices on a positive- or subtractive-decode ISA bus.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Kms",
        guid: guid!("ec3a978d-7c4e-48fa-9abe-6ad91cc8f811"),
        description: "The Key Management Service (KMS) protocol as defined in the UEFI 2.3.1 specification is to provides services to generate, store, retrieve, and manage cryptographic keys. The intention is to specify a simple generic protocol that could be used for many implementations.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "LegacyRegion2",
        guid: guid!("70101eaf-0085-440c-b356-8ee36fef24f0"),
        description: "The Legacy Region Protocol controls the read, write and boot-lock attributes for the region 0xC0000 to 0xFFFFF.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "LegacySpiController",
        guid: guid!("39136fc7-1a11-49de-bf35-0e78ddb524fc"),
        description: "This file defines the Legacy SPI Controller Protocol.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "LegacySpiFlash",
        guid: guid!("f01bed57-04bc-4f3f-9660-d6f2ea228259"),
        description: "This file defines the Legacy SPI Flash Protocol.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "LegacySpiSmmController",
        guid: guid!("62331b78-d8d0-4c8c-8ccb-d27dfe32db9b"),
        description: "This file defines the Legacy SPI SMM Controller Protocol.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "LegacySpiSmmFlash",
        guid: guid!("5e3848d4-0db5-4fc0-9729-3f353d4f879f"),
        description: "This file defines the Legacy SPI SMM Flash Protocol.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "LoadFile",
        guid: guid!("56ec3091-954c-11d2-8e3f-00a0c969723b"),
        description: "Load File protocol as defined in the UEFI 2.0 specification. The load file protocol exists to supports the addition of new boot devices, and to support booting from devices that do not map well to file system.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "LoadFile2",
        guid: guid!("4006c0c1-fcb3-403e-996d-4a6c8724e06d"),
        description: "Load File protocol as defined in the UEFI 2.0 specification. Load file protocol exists to supports the addition of new boot devices, and to support booting from devices that do not map well to file system.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "LoadedImage",
        guid: guid!("5b1b31a1-9562-11d2-8e3f-00a0c969723b"),
        description: "UEFI 2.0 Loaded image protocol definition. Every EFI driver and application is passed an image handle when it is loaded.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "ManagedNetwork",
        guid: guid!("7ab33a91-ace5-4326-b572-e7ee33d39f16"),
        description: "EFI_MANAGED_NETWORK_SERVICE_BINDING_PROTOCOL as defined in UEFI 2.0. EFI_MANAGED_NETWORK_PROTOCOL as defined in UEFI 2.0.",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "MemoryAccept",
        guid: guid!("38c74800-5590-4db4-a0f3-675d9b8e8026"),
        description: "The file provides the protocol to provide interface to accept memory.",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "MemoryAttribute",
        guid: guid!("f4560cf6-40ec-4b4a-a192-bf1d57d0b189"),
        description: "EFI Memory Attribute Protocol provides retrieval and update service for memory attributes in EFI environment.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "Metronome",
        guid: guid!("26baccb2-6f42-11d4-bce7-0080c73c8881"),
        description: "Metronome Architectural Protocol as defined in PI SPEC VOLUME 2 DXE This code abstracts the DXE core to provide delay services.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "MonotonicCounter",
        guid: guid!("1da97072-bddc-4b30-99f1-72a0b56fff2a"),
        description: "Monotonic Counter Architectural Protocol as defined in PI SPEC VOLUME 2 DXE This code provides the services required to access the system's monotonic counter",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "MpService",
        guid: guid!("3fdda605-a76e-4f46-ad29-12f4531b3d08"),
        description: "When installed, the MP Services Protocol produces a collection of services that are needed for MP management. The MP Services Protocol provides a generalized way of performing following tasks: - Retrieving information of multi-processor environment and MP-related status of specific processors.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Mtftp4",
        guid: guid!("78247c57-63db-4708-99c2-a8b4a9a61f6b"),
        description: "EFI Multicast Trivial File Transfer Protocol Definition",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Mtftp6",
        guid: guid!("bf0a78ba-ec29-49cf-a1c9-7ae54eab6a51"),
        description: "UEFI Multicast Trivial File Transfer Protocol v6 Definition, which is built upon the EFI UDPv6 Protocol and provides basic services for client-side unicast and/or multicast TFTP operations.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "NetworkInterfaceIdentifier",
        guid: guid!("e18541cd-f755-4f73-928d-643c8a79b229"),
        description: "EFI Network Interface Identifier Protocol.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "NvdimmLabel",
        guid: guid!("d40b6b80-97d5-4282-bb1d-223a16918058"),
        description: "EFI NVDIMM Label Protocol Definition The EFI NVDIMM Label Protocol is used to Provides services that allow management of labels contained in a Label Storage Area that are associated with a specific NVDIMM Device Path.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "NvmExpressPassthru",
        guid: guid!("52c78312-8edc-4233-98f2-1a1aa5e388a5"),
        description: "This protocol provides services that allow NVM Express commands to be sent to an NVM Express controller or to a specific namespace in a NVM Express controller. This protocol interface is optimized for storage.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "PartitionInfo",
        guid: guid!("8cf2f62c-bc9b-4821-808d-ec9ec421a1a0"),
        description: "This file defines the EFI Partition Information Protocol.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "Pcd",
        guid: guid!("11b34006-d85b-4d0a-a290-d5a571310ef7"),
        description: "Native Platform Configuration Database (PCD) Protocol Different with the EFI_PCD_PROTOCOL defined in PI 1.2 specification, the native PCD protocol provide interfaces for dynamic and dynamic-ex type PCD. The interfaces in dynamic type PCD do not require the token space guid as parameter, but interfaces in dynamic-ex type PCD require token space guid as parameter.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "PcdInfo",
        guid: guid!("5be40f57-fa68-4610-bbbf-e9c5fcdad365"),
        description: "Native Platform Configuration Database (PCD) INFO PROTOCOL. The protocol that provides additional information about items that reside in the PCD database.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciEnumerationComplete",
        guid: guid!("30cfe3e7-3de1-4586-be20-deaba1b3b793"),
        description: "PCI Enumeration Complete Protocol as defined in the PI 1.1 specification. This protocol indicates that pci enumeration complete",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciHostBridgeResourceAllocation",
        guid: guid!("cf8034be-6768-4d8b-b739-7cce683a9fbe"),
        description: "This file declares PCI Host Bridge Resource Allocation Protocol which provides the basic interfaces to abstract a PCI host bridge resource allocation. This protocol is mandatory if the system includes PCI devices.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciHotPlugInit",
        guid: guid!("aa0e8bc1-dabc-46b0-a844-37b8169b2bea"),
        description: "This file declares EFI PCI Hot Plug Init Protocol. This protocol provides the necessary functionality to initialize the Hot Plug Controllers (HPCs) and the buses that they control.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciHotPlugRequest",
        guid: guid!("19cb87ab-2cb9-4665-8360-ddcf6054f79d"),
        description: "Provides services to notify the PCI bus driver that some events have happened in a hot-plug controller (such as a PC Card socket, or PHPC), and to ask the PCI bus driver to create or destroy handles for PCI-like devices. A hot-plug capable PCI bus driver should produce the EFI PCI Hot Plug Request protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciIo",
        guid: guid!("4cf5b200-68b8-4ca5-9eec-b23e3f50029a"),
        description: "EFI PCI I/O Protocol provides the basic Memory, I/O, PCI configuration, and DMA interfaces that a driver uses to access its PCI controller.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciOverride",
        guid: guid!("b5b35764-460c-4a06-99fc-77a17c1b5ceb"),
        description: "This file declares EFI PCI Override protocol which provides the interface between the PCI bus driver/PCI Host Bridge Resource Allocation driver and an implementation's driver to describe the unique features of a platform. This protocol is optional.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciPlatform",
        guid: guid!("07d75280-27d4-4d69-90d0-5643e238b341"),
        description: "This file declares PlatfromOpRom protocols that provide the interface between the PCI bus driver/PCI Host Bridge Resource Allocation driver and a platform-specific driver to describe the unique features of a platform. This protocol is optional.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "PciRootBridgeIo",
        guid: guid!("2f707ebb-4a1a-11d4-9a38-0090273fc14d"),
        description: "PCI Root Bridge I/O protocol as defined in the UEFI 2.0 specification. PCI Root Bridge I/O protocol is used by PCI Bus Driver to perform PCI Memory, PCI I/O, and PCI Configuration cycles on a PCI Root Bridge.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "PiPcd",
        guid: guid!("13a3f0f6-264a-3ef0-f2e0-dec512342f34"),
        description: "Platform Configuration Database (PCD) Protocol defined in PI 1.2 Vol3 A platform database that contains a variety of current platform settings or directives that can be accessed by a driver or application. PI PCD protocol only provide the accessing interfaces for Dynamic-Ex type PCD.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "PiPcdInfo",
        guid: guid!("fd0f4478-0efd-461d-ba2d-e58c45fd5f5e"),
        description: "Platform Configuration Database (PCD) Info Protocol defined in PI 1.2.1 Vol3. The protocol that provides additional information about items that reside in the PCD database.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Pkcs7Verify",
        guid: guid!("47889fb2-d671-4fab-a0ca-df0e44df70d6"),
        description: "EFI_PKCS7_VERIFY_PROTOCOL as defined in UEFI 2.5. The EFI_PKCS7_VERIFY_PROTOCOL is used to verify data signed using PKCS#7 formatted authentication.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "PxeBaseCode",
        guid: guid!("03c4e603-ac28-11d3-9a2d-0090273fc14d"),
        description: "EFI PXE Base Code Protocol definitions, which is used to access PXE-compatible devices for network access and network booting.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "PxeBaseCodeCallBack",
        guid: guid!("245dca21-fb7b-11d3-8f01-00a0c969723b"),
        description: "It is invoked when the PXE Base Code Protocol is about to transmit, has received, or is waiting to receive a packet.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "RamDisk",
        guid: guid!("ab38a0df-6873-44a9-87e6-d4eb56148449"),
        description: "This file defines the EFI RAM Disk Protocol.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "RealTimeClock",
        guid: guid!("27cfac87-46cc-11d4-9a38-0090273fc14d"),
        description: "Real Time clock Architectural Protocol as defined in PI Specification VOLUME 2 DXE This code abstracts time and data functions. Used to provide Time and date related EFI runtime services.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "RedfishDiscover",
        guid: guid!("5db12509-4550-4347-96b3-73c0ff6e869f"),
        description: "This file defines the EFI Redfish Discover Protocol interface. (C) Copyright 2021 Hewlett Packard Enterprise Development LP<BR> SPDX-License-Identifier: BSD-2-Clause-Patent",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "RegularExpressionProtocol",
        guid: guid!("b3f79d9a-436c-dc11-b052-cd85df524ce6"),
        description: "This section defines the Regular Expression Protocol. This protocol isused to match Unicode strings against Regular Expression patterns.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "ReportStatusCodeHandler",
        guid: guid!("86212936-0e76-41c8-a03a-2af2fc1c39e2"),
        description: "This protocol provide registering and unregistering services to status code consumers while in DXE.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "Reset",
        guid: guid!("27cfac88-46cc-11d4-9a38-0090273fc14d"),
        description: "Reset Architectural Protocol as defined in PI Specification VOLUME 2 DXE Used to provide ResetSystem runtime services The ResetSystem () UEFI 2.0 service is added to the EFI system table and the EFI_RESET_ARCH_PROTOCOL_GUID protocol is registered with a NULL pointer.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "ResetNotification",
        guid: guid!("9da34ae0-eaf9-4bbf-8ec3-fd60226c44be"),
        description: "EFI Reset Notification Protocol as defined in UEFI 2.7. This protocol provides services to register for a notification when ResetSystem is called.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "Rest",
        guid: guid!("0db48a36-4e54-ea9c-9b09-1ea5be3a660b"),
        description: "This file defines the EFI REST Protocol interface.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "RestEx",
        guid: guid!("55648b91-0e7d-40a3-a9b3-a815d7eadf97"),
        description: "This file defines the EFI REST EX Protocol interface. It is split into the following two main sections.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "RestJsonStructure",
        guid: guid!("a9a048f6-48a0-4714-b7da-a9ad87d4dac9"),
        description: "This file defines the EFI REST JSON Structure Protocol interface. (C) Copyright 2020 Hewlett Packard Enterprise Development LP<BR> SPDX-License-Identifier: BSD-2-Clause-Patent",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Rng",
        guid: guid!("3152bca5-eade-433d-862e-c01cdc291f44"),
        description: "EFI_RNG_PROTOCOL as defined in UEFI 2.4. The UEFI Random Number Generator Protocol is used to provide random bits for use in applications, or entropy for seeding other random number generators.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "Runtime",
        guid: guid!("b7dfb4e1-052f-449f-87be-9818fc91b733"),
        description: "Runtime Architectural Protocol as defined in PI Specification VOLUME 2 DXE Allows the runtime functionality of the DXE Foundation to be contained in a separate driver. It also provides hooks for the DXE Foundation to export information that is needed at runtime.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "S3SaveState",
        guid: guid!("e857caf6-c046-45dc-be3f-ee0765fba887"),
        description: "S3 Save State Protocol as defined in PI 1.6(Errata A) Specification VOLUME 5 Standard. This protocol is used by DXE PI module to store or record various IO operations to be replayed during an S3 resume.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "S3SmmSaveState",
        guid: guid!("320afe62-e593-49cb-a9f1-d4c2f4af014c"),
        description: "S3 SMM Save State Protocol as defined in PI1.2 Specification VOLUME 5 Standard. The EFI_S3_SMM_SAVE_STATE_PROTOCOL publishes the PI SMMboot script abstractions On an S3 resume boot path the data stored via this protocol is replayed in the order it was stored.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "ScsiIo",
        guid: guid!("932f47e6-2362-4002-803e-3cd54b138f85"),
        description: "EFI_SCSI_IO_PROTOCOL as defined in UEFI 2.0. This protocol is used by code, typically drivers, running in the EFI boot services environment to access SCSI devices.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "ScsiPassThruExt",
        guid: guid!("143b7632-b81b-4cb7-abd3-b625a5b9bffe"),
        description: "EFI_EXT_SCSI_PASS_THRU_PROTOCOL as defined in UEFI 2.0. This protocol provides services that allow SCSI Pass Thru commands to be sent to SCSI devices attached to a SCSI channel.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "SdMmcPassThru",
        guid: guid!("716ef0d9-ff83-4f69-81e9-518bd39a8e70"),
        description: "The EFI_SD_MMC_PASS_THRU_PROTOCOL provides the ability to send SD/MMC Commands to any SD/MMC device attached to the SD compatible pci host controller.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Security",
        guid: guid!("a46423e3-4617-49f1-b9ff-d1bfa9115839"),
        description: "Security Architectural Protocol as defined in PI Specification VOLUME 2 DXE Used to provide Security services. Specifically, depending upon the authentication state of a discovered driver in a Firmware Volume, the portable DXE Core Dispatcher will call into the Security Architectural Protocol (SAP) with the authentication state of the driver.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Security2",
        guid: guid!("94ab2f58-1438-4ef1-9152-18941a3a0e68"),
        description: "Security2 Architectural Protocol as defined in PI Specification1.2.1 VOLUME 2 DXE Abstracts security-specific functions from the DXE Foundation of UEFI Image Verification, Trusted Computing Group (TCG) measured boot, and User Identity policy for image loading and consoles. This protocol must be produced by a boot service or runtime DXE driver.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "SecurityPolicy",
        guid: guid!("78e4d245-cd4d-4a05-a2ba-4743e86cfcab"),
        description: "Security Policy protocol as defined in PI Specification VOLUME 2 DXE",
    },
    ProtocolEntry {
        category: "Console, Input & Serial I/O",
        name: "SerialIo",
        guid: guid!("bb25cf6f-f1d4-11d2-9a0c-0090273fc1fd"),
        description: "Serial IO protocol as defined in the UEFI 2.0 specification. Abstraction of a basic serial device.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "Shell",
        guid: guid!("6302d008-7f9b-4f30-87ac-60c9fef5da4e"),
        description: "EFI Shell protocol as defined in the UEFI Shell 2.0 specification including errata. (C) Copyright 2014 Hewlett-Packard Development Company, L.P.<BR>",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "ShellDynamicCommand",
        guid: guid!("3c7200e9-005f-4ea4-87de-a3dfac8a27c3"),
        description: "EFI Shell Dynamic Command registration protocol (C) Copyright 2012-2014 Hewlett-Packard Development Company, L.P.<BR>",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "ShellParameters",
        guid: guid!("752f3136-4e16-4fdc-a22a-e5f46812f4ca"),
        description: "EFI Shell protocol as defined in the UEFI Shell 2.0 specification.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "SimpleFileSystem",
        guid: guid!("964e5b22-6459-11d2-8e39-00a0c969723b"),
        description: "SimpleFileSystem protocol as defined in the UEFI 2.0 specification. The SimpleFileSystem protocol is the programmatic access to the FAT (12,16,32) file system specified in UEFI 2.0.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "SimpleNetwork",
        guid: guid!("a19832b9-ac25-11d3-9a2d-0090273fc14d"),
        description: "The EFI_SIMPLE_NETWORK_PROTOCOL provides services to initialize a network interface, transmit packets, receive packets, and close a network interface. Basic network device abstraction.",
    },
    ProtocolEntry {
        category: "Console, Input & Serial I/O",
        name: "SimplePointer",
        guid: guid!("31878c87-0b75-11d5-9a4f-0090273fc14d"),
        description: "Simple Pointer protocol from the UEFI 2.0 specification. Abstraction of a very simple pointer device like a mouse or trackball.",
    },
    ProtocolEntry {
        category: "Console, Input & Serial I/O",
        name: "SimpleTextIn",
        guid: guid!("387477c1-69c7-11d2-8e39-00a0c969723b"),
        description: "Simple Text Input protocol from the UEFI 2.0 specification. Abstraction of a very simple input device like a keyboard or serial terminal.",
    },
    ProtocolEntry {
        category: "Console, Input & Serial I/O",
        name: "SimpleTextInEx",
        guid: guid!("dd9e7534-7762-4698-8c14-f58517a625aa"),
        description: "Simple Text Input Ex protocol from the UEFI 2.0 specification. This protocol defines an extension to the EFI_SIMPLE_TEXT_INPUT_PROTOCOL which exposes much more state and modifier information from the input device, also allows one to register a notification for a particular keystroke.",
    },
    ProtocolEntry {
        category: "Console, Input & Serial I/O",
        name: "SimpleTextOut",
        guid: guid!("387477c2-69c7-11d2-8e39-00a0c969723b"),
        description: "Simple Text Out protocol from the UEFI 2.0 specification. Abstraction of a very simple text based output device like VGA text mode or a serial terminal.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "SmartCardEdge",
        guid: guid!("d317f29b-a325-4712-9bf1-c61954dc198c"),
        description: "The Smart Card Edge Protocol provides an abstraction for device to provide Smart Card support. This protocol allows UEFI applications to interface with a Smart Card during boot process for authentication or data signing/decryption, especially if the application has to make use of PKI.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "SmartCardReader",
        guid: guid!("2a4d1adf-21dc-4b81-a42f-8b8ee2380060"),
        description: "The UEFI Smart Card Reader Protocol provides an abstraction for device to provide smart card reader support. This protocol is very close to Part 5 of PC/SC workgroup specifications and provides an API to applications willing to communicate with a smart card or a smart card reader.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SmbusHc",
        guid: guid!("e49d33ed-513d-4634-b698-6f55aa751c1b"),
        description: "The file provides basic SMBus host controller management and basic data transactions over the SMBus.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SpiConfiguration",
        guid: guid!("85a6d3e6-b65b-4afc-b38f-c6d54af6ddc8"),
        description: "This file defines the SPI Configuration Protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SpiHc",
        guid: guid!("c74e5db2-fa96-4ae2-b399-15977fe3002d"),
        description: "This file defines the SPI Host Controller Protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SpiNorFlash",
        guid: guid!("b57ec3fe-f833-4ba6-8578-2a7d6a87444b"),
        description: "This file defines the SPI NOR Flash Protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SpiSmmConfiguration",
        guid: guid!("995c6eca-171b-45fd-a3aa-fd4c9c9def59"),
        description: "This file defines the SPI SMM Configuration Protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SpiSmmHc",
        guid: guid!("e9f02217-2093-4470-8a54-5c2cffe73ecb"),
        description: "This file defines the SPI SMM Host Controller Protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SpiSmmNorFlash",
        guid: guid!("aab18f19-fe14-4666-8604-87ff6d662c9a"),
        description: "This file defines the SPI SMM NOR Flash Protocol.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "StatusCode",
        guid: guid!("d2b2b828-0826-48a7-b3df-983c006024f0"),
        description: "Status code Runtime Protocol as defined in PI Specification 1.4a VOLUME 2 DXE",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "StorageSecurityCommand",
        guid: guid!("c88b0b6d-0dfc-49a7-9cb4-49074b4c3a78"),
        description: "EFI Storage Security Command Protocol as defined in UEFI 2.3.1 specification. This protocol is used to abstract mass storage devices to allow code running in the EFI boot services environment to send security protocol commands to mass storage devices without specific knowledge of the type of device or controller that manages the device.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SuperIo",
        guid: guid!("215fdd18-bd50-4feb-890b-58ca0b4739e9"),
        description: "The Super I/O Protocol is installed by the Super I/O driver. The Super I/O driver is a UEFI driver model compliant driver.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "SuperIoControl",
        guid: guid!("b91978df-9fc1-427d-bb05-4c828455ca27"),
        description: "The Super I/O Control Protocol is installed by the Super I/O driver. It provides the low-level services for SIO devices that enable them to be used in the UEFI driver model.",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "Supplicant",
        guid: guid!("54fcc43e-aa89-4333-9a85-cdea24051e9e"),
        description: "This file defines the EFI Supplicant Protocol.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "TapeIo",
        guid: guid!("1e93e633-d65a-459e-ab84-93d9ec266d18"),
        description: "EFI_TAPE_IO_PROTOCOL as defined in the UEFI 2.0. Provide services to control and access a tape device.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "Tcg2Protocol",
        guid: guid!("607f766c-7455-42be-930b-e4d76db2720f"),
        description: "TPM2 Protocol as defined in TCG PC Client Platform EFI Protocol Specification Family \"2.0\". See http://trustedcomputinggroup.org for the latest specification",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "TcgService",
        guid: guid!("f541796d-a62e-4954-a775-9584f61b9cdd"),
        description: "TCG Service Protocol as defined in TCG_EFI_Protocol_1_22_Final See http://trustedcomputinggroup.org for the latest specification",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Tcp4",
        guid: guid!("65530bc7-a359-410f-b010-5aadc7ec2b62"),
        description: "EFI TCPv4(Transmission Control Protocol version 4) Protocol Definition The EFI TCPv4 Service Binding Protocol is used to locate EFI TCPv4 Protocol drivers to create and destroy child of the driver to communicate with other host using TCP protocol. The EFI TCPv4 Protocol provides services to send and receive data stream.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Tcp6",
        guid: guid!("46e44855-bd60-4ab7-ab0d-a679b9447d77"),
        description: "EFI TCPv6(Transmission Control Protocol version 6) Protocol Definition The EFI TCPv6 Service Binding Protocol is used to locate EFI TCPv6 Protocol drivers to create and destroy child of the driver to communicate with other host using TCP protocol. The EFI TCPv6 Protocol provides services to send and receive data stream.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "Timer",
        guid: guid!("26baccb3-6f42-11d4-bce7-0080c73c8881"),
        description: "Timer Architectural Protocol as defined in PI Specification VOLUME 2 DXE This code is used to provide the timer tick for the DXE core.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "Timestamp",
        guid: guid!("afbfde41-2e6e-4262-ba65-62b9236e5495"),
        description: "EFI Timestamp Protocol as defined in UEFI2.4 Specification. Used to provide a platform independent interface for retrieving a high resolution timestamp counter.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "Tls",
        guid: guid!("00ca959f-6cfa-4db1-95bc-e46c47514390"),
        description: "EFI TLS Protocols as defined in UEFI 2.5. The EFI TLS Service Binding Protocol is used to locate EFI TLS Protocol drivers to create and destroy child of the driver to communicate with other host using TLS protocol.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "TlsConfig",
        guid: guid!("1682fe44-bd7a-4407-b7c7-dca37ca3922d"),
        description: "EFI TLS Configuration Protocol as defined in UEFI 2.5. The EFI TLS Configuration Protocol provides a way to set and get TLS configuration.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Udp4",
        guid: guid!("3ad9df29-4501-478d-b1f8-7f7fe70e50f3"),
        description: "UDP4 Service Binding Protocol as defined in UEFI specification. The EFI UDPv4 Protocol provides simple packet-oriented services to transmit and receive UDP packets.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Udp6",
        guid: guid!("4f948815-b4b9-43cb-8a33-90e060b34955"),
        description: "The EFI UDPv6 (User Datagram Protocol version 6) Protocol Definition, which is built upon the EFI IPv6 Protocol and provides simple packet-oriented services to transmit and receive UDP packets.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "UfsDeviceConfig",
        guid: guid!("b81bfab0-0eb3-4cf9-8465-7fa986361664"),
        description: "This file defines the EFI UFS Device Config Protocol.",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "UnicodeCollation",
        guid: guid!("a4c751fc-23ae-4c3e-92e9-4964cf63f349"),
        description: "Unicode Collation protocol that follows the UEFI 2.0 specification. This protocol is used to allow code running in the boot services environment to perform lexical comparison functions on Unicode strings for given languages.",
    },
    ProtocolEntry {
        category: "USB",
        name: "Usb2HostController",
        guid: guid!("3e745226-9818-45b6-a2ac-d7cd0e8ba2bc"),
        description: "EFI_USB2_HC_PROTOCOL as defined in UEFI 2.0. The USB Host Controller Protocol is used by code, typically USB bus drivers, running in the EFI boot services environment, to perform data transactions over a USB bus.",
    },
    ProtocolEntry {
        category: "USB",
        name: "UsbFunctionIo",
        guid: guid!("32d2963a-fe5d-4f30-b633-6e5dc55803cc"),
        description: "The USB Function Protocol provides an I/O abstraction for a USB Controller operating in Function mode (also commonly referred to as Device, Peripheral, or Target mode) and the mechanisms by which the USB Function can communicate with the USB Host. It is used by other UEFI drivers or applications to perform data transactions and basic USB controller management over a USB Function port.",
    },
    ProtocolEntry {
        category: "USB",
        name: "UsbIo",
        guid: guid!("2b2f68d6-0cd2-44cf-8e8b-bba20b1b5b75"),
        description: "EFI Usb I/O Protocol as defined in UEFI specification. This protocol is used by code, typically drivers, running in the EFI boot services environment to access USB devices like USB keyboards, mice and mass storage devices.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "UserCredential",
        guid: guid!("71ee5e94-65b9-45d5-821a-3a4d86cfe6be"),
        description: "UEFI 2.2 User Credential Protocol definition.It has been removed from UEFI 2.3.1 and replaced by EFI_USER_CREDENTIAL2_PROTOCOL. Attached to a device handle, this protocol identifies a single means of identifying the user.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "UserCredential2",
        guid: guid!("e98adb03-b8b9-4af8-ba20-26e9114cbce5"),
        description: "UEFI 2.3.1 User Credential Protocol definition. Attached to a device handle, this protocol identifies a single means of identifying the user.",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "UserManager",
        guid: guid!("6fd5b00c-d426-4283-9887-6cf5cf1cb1fe"),
        description: "UEFI User Manager Protocol definition. This protocol manages user profiles.",
    },
    ProtocolEntry {
        category: "NVRAM Variable Services",
        name: "Variable",
        guid: guid!("1e5668e2-8481-11d4-bcf1-0080c73c8881"),
        description: "Variable Architectural Protocol as defined in PI Specification VOLUME 2 DXE This provides the services required to get and set environment variables. This protocol must be produced by a runtime DXE driver and may be consumed only by the DXE Foundation.",
    },
    ProtocolEntry {
        category: "NVRAM Variable Services",
        name: "VariableWrite",
        guid: guid!("6441f818-6362-4e44-b570-7dba31dd2453"),
        description: "Variable Write Architectural Protocol as defined in PI Specification VOLUME 2 DXE This provides the services required to set nonvolatile environment variables. This protocol must be produced by a runtime DXE driver and may be consumed only by the DXE Foundation.",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "VlanConfig",
        guid: guid!("9e23d768-d2f3-4366-9fc3-3a7aba864374"),
        description: "EFI VLAN Config protocol is to provide manageability interface for VLAN configuration.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "WatchdogTimer",
        guid: guid!("665e3ff5-46cc-11d4-9a38-0090273fc14d"),
        description: "Watchdog Timer Architectural Protocol as defined in PI Specification VOLUME 2 DXE Used to provide system watchdog timer services",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "WiFi",
        guid: guid!("0da55bc9-45f8-4bb4-8719-5224f18a4d45"),
        description: "This file provides management service interfaces of 802.11 MAC layer. It is used by network applications (and drivers) to establish wireless connection with an access point (AP).",
    },
    ProtocolEntry {
        category: "Bluetooth & Wireless",
        name: "WiFi2",
        guid: guid!("1b0fb9bf-699d-4fdd-a7c3-2546681bf63b"),
        description: "This file defines the EFI Wireless MAC Connection II Protocol.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "AtaAtapiPolicy",
        guid: guid!("e59cd769-5083-4f26-9094-6c919f916c4e"),
        description: "ATA ATAPI Policy protocol is produced by platform and consumed by AtaAtapiPassThruDxe driver.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "BootLogo",
        guid: guid!("cdea2bd3-fc25-4c1c-b97c-b31186064990"),
        description: "Boot Logo protocol is used to convey information of Logo dispayed during boot.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "BootLogo2",
        guid: guid!("4b5dc1df-1eaa-48b2-a7e9-eac489a00b5c"),
        description: "Boot Logo 2 Protocol is used to convey information of Logo dispayed during boot. The Boot Logo 2 Protocol is a replacement for the Boot Logo Protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "CxlIo",
        guid: guid!("8fac60b2-bbc1-41de-a797-9875cdd3a8f8"),
        description: "EFI CXL I/O Protocol provides the interfaces to interact with the CXL-specific subsystems of CXL devices. Other interactions with CXL devices should be routed through EFI_PCI_IO_PROTOCOL",
    },
    ProtocolEntry {
        category: "Security, Measured/Secure Boot & Crypto",
        name: "DeviceSecurity",
        guid: guid!("5d6b38c8-5510-4458-b48d-9581cfa7b00d"),
        description: "Device Security Protocol definition. It is used to authenticate a device based upon the platform policy.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "DisplayProtocol",
        guid: guid!("9bbe29e9-fda1-41ec-ad52-452213742d2e"),
        description: "FormDiplay protocol to show Form",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "EbcSimpleDebugger",
        guid: guid!("2a72d11e-7376-40f6-9c68-23fa2fe363f1"),
        description: "EBC Simple Debugger protocol for debug EBC code.",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "EbcVmTest",
        guid: guid!("aaeaccfd-f27b-4c17-b610-75ca1f2dfb52"),
        description: "EBC VM Test protocol for test purposes.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "EsrtManagement",
        guid: guid!("a340c064-723c-4a9c-a4dd-d5b47a26fbb0"),
        description: "The Esrt Management Protocol used to register/set/update an updatable firmware resource .",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "FaultTolerantWrite",
        guid: guid!("3ebd9e82-2c78-4de6-9786-8d4bfcb7c881"),
        description: "Fault Tolerant Write protocol provides boot-time service for fault tolerant write capability for block devices. The protocol provides for non-volatile storage of the intermediate data and private information a caller would need to recover from a critical fault, such as a power failure.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "FileExplorer",
        guid: guid!("2c03c536-4594-4515-9e7a-d3d204fe1363"),
        description: "This file explorer protocol defines defines a set of interfaces for how to do file explorer.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "FirmwareManagementProgress",
        guid: guid!("1849bda2-6952-4e86-a1db-559a3c479df1"),
        description: "EDK II Firmware Management Progress Protocol.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "FormBrowserEx",
        guid: guid!("1f73b18d-4630-43c1-a1de-6f80855d7da4"),
        description: "Extension Form Browser Protocol provides the services that can be used to register the different hot keys for the standard Browser actions described in UEFI specification.",
    },
    ProtocolEntry {
        category: "HII & Forms",
        name: "FormBrowserEx2",
        guid: guid!("a770c357-b693-4e6d-a6cf-d21c728e550b"),
        description: "Extension Form Browser Protocol provides the services that can be used to register the different hot keys for the standard Browser actions described in UEFI specification.",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "GenericMemoryTest",
        guid: guid!("309de7f1-7f5e-4ace-b49c-531be5aa95ef"),
        description: "This protocol defines the generic memory test interfaces in Dxe phase.",
    },
    ProtocolEntry {
        category: "CPU & Multi-Processor",
        name: "IoMmu",
        guid: guid!("4e939de9-d948-4b0f-88ed-e6e1ce517c1e"),
        description: "EFI IOMMU Protocol.",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "LoadPe32Image",
        guid: guid!("5cb5c776-60d5-45ee-883c-452708cd743f"),
        description: "Load Pe32 Image protocol enables loading and unloading EFI images into memory and executing those images. This protocol uses File Device Path to get an EFI image.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "LockBox",
        guid: guid!("bd445d79-b7ad-4f04-9ad8-29bd2040eb3c"),
        description: "LockBox protocol header file. This is used to resolve dependency problem.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "MediaSanitize",
        guid: guid!("0d799a99-25af-429e-9272-d0b27d6d5f14"),
        description: "This file defines the Media Sanitize Protocol.",
    },
    ProtocolEntry {
        category: "PCI, Bus & Local Device Access",
        name: "NonDiscoverableDevice",
        guid: guid!("0d51905b-b77e-452a-a2c0-eca0cc8d514a"),
        description: "Protocol to describe devices that are not on a discoverable bus",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "PeCoffImageEmulator",
        guid: guid!("96f46153-97a7-4793-acc1-fa19bf78ea97"),
        description: "Copyright (c) 2019, Linaro, Ltd. All rights reserved.<BR> SPDX-License-Identifier: BSD-2-Clause-Patent",
    },
    ProtocolEntry {
        category: "Boot, Image Loading & Device Path",
        name: "PlatformBootManager",
        guid: guid!("aa17add4-756c-460d-94b8-4388d7fb3e59"),
        description: "Copyright (c) 2019, NVIDIA CORPORATION. All rights reserved.",
    },
    ProtocolEntry {
        category: "Graphics & Display",
        name: "PlatformLogo",
        guid: guid!("53cd299f-2bc1-40c0-8c07-23f64fdb30e0"),
        description: "The Platform Logo Protocol defines the interface to get the Platform logo image with the display attribute.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "PlatformSpecificResetFilter",
        guid: guid!("695d7835-8d47-4c11-ab22-fa8acce7ae7a"),
        description: "This Protocol provides services to register a platform specific reset filter for ResetSystem(). A reset filter evaluates the parameters passed to ResetSystem() and converts a ResetType of EfiResetPlatformSpecific to a non-platform specific reset type.",
    },
    ProtocolEntry {
        category: "Timers, Clock, Reset & Power",
        name: "PlatformSpecificResetHandler",
        guid: guid!("2df6ba0b-7092-440d-bd04-fb091ec3f3c1"),
        description: "This protocol provides services to register a platform specific handler for ResetSystem(). The registered handlers are called after the UEFI 2.7 Reset Notifications are processed",
    },
    ProtocolEntry {
        category: "Debug & Misc Utility",
        name: "Print2",
        guid: guid!("f05976ef-83f1-4f3d-8619-f7595d41e538"),
        description: "Produces EFI_PRINT2_PROTOCOL and EFI_PRINT2S_PROTOCOL. These protocols define basic print functions to  print the format unicode and ascii string.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "SdMmcOverride",
        guid: guid!("eaf9e3c1-c9cd-46db-a5e5-5a124c832323"),
        description: "Protocol to describe overrides required to support non-standard SDHCI implementations",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "SmmFaultTolerantWrite",
        guid: guid!("3868fc3b-7e45-43a7-906c-4ba47de1754d"),
        description: "SMM Fault Tolerant Write protocol is related to EDK II-specific implementation of FTW, provides boot-time service for fault tolerant write capability for block devices in EFI SMM environment. The protocol provides for non-volatile storage of the intermediate data and private information a caller would need to recover from a critical fault, such as a power failure.",
    },
    ProtocolEntry {
        category: "Firmware Update, Volumes & Capsules",
        name: "SmmFirmwareVolumeBlock",
        guid: guid!("d326d041-bd31-4c01-b5a8-628be87f0653"),
        description: "SMM Firmware Volume Block protocol is related to EDK II-specific implementation of FVB driver, provides control over block-oriented firmware devices and is intended to use in the EFI SMM environment.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "SmmSwapAddressRange",
        guid: guid!("67c4f112-3385-4e55-9c5b-c05b717c4228"),
        description: "The EFI_SMM_SWAP_ADDRESS_RANGE_PROTOCOL is related to EDK II-specific implementation and used to abstract the swap operation of boot block and backup block of FV in EFI SMM environment. This swap is especially needed when updating the boot block of FV.",
    },
    ProtocolEntry {
        category: "NVRAM Variable Services",
        name: "SmmVarCheck",
        guid: guid!("b0d8f3c1-b7de-4c11-bc89-2fb562c8c411"),
        description: "SMM variable check definitions, it reuses the interface definitions of variable check.",
    },
    ProtocolEntry {
        category: "NVRAM Variable Services",
        name: "SmmVariable",
        guid: guid!("ed32d533-99e6-4209-9cc0-2d72cdd998a7"),
        description: "EFI SMM Variable Protocol is related to EDK II-specific implementation of variables and intended for use as a means to store data in the EFI SMM environment.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "SwapAddressRange",
        guid: guid!("1259f60d-b754-468e-a789-4db85d55e87e"),
        description: "The EFI_SWAP_ADDRESS_RANGE_PROTOCOL is used to abstract the swap operation of boot block and backup block of FV. This swap is especially needed when updating the boot block of FV.",
    },
    ProtocolEntry {
        category: "Block / Disk / File Storage",
        name: "UfsHostController",
        guid: guid!("ebc01af5-07a9-489e-b7ce-dc089e459b2f"),
        description: "EDKII Universal Flash Storage Host Controller Protocol.",
    },
    ProtocolEntry {
        category: "USB",
        name: "UsbEthernetProtocol",
        guid: guid!("8d8969cc-feb0-4303-b21a-1f116f385643"),
        description: "Header file contains code for USB Ethernet Protocol definitions",
    },
    ProtocolEntry {
        category: "NVRAM Variable Services",
        name: "VariableLock",
        guid: guid!("cd3d0a05-9e24-437c-a891-1ee053db7638"),
        description: "Variable Lock Protocol is related to EDK II-specific implementation of variables and intended for use as a means to mark a variable read-only after the event EFI_END_OF_DXE_EVENT_GUID is signaled.",
    },
    ProtocolEntry {
        category: "NVRAM Variable Services",
        name: "VariablePolicy",
        guid: guid!("81d1675c-86f6-48df-bd95-9a6e4f0925c3"),
        description: "(no description found)",
    },
    ProtocolEntry {
        category: "Networking (Link/IP/Transport)",
        name: "Dpc",
        guid: guid!("480f8ae9-0c46-4aa9-bc89-db9fba619806"),
        description: "EFI Deferred Procedure Call Protocol.",
    },
    ProtocolEntry {
        category: "Networking (Boot/HTTP/Higher-Level)",
        name: "HttpCallback",
        guid: guid!("611114f1-a37b-4468-a436-5bdda16aa240"),
        description: "This file defines the EDKII HTTP Callback Protocol interface.",
    },
];
